In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.model_selection import train_test_split
import time
import warnings
warnings.filterwarnings('ignore')

In [2]:
dataset = pd.read_csv('heart.csv')

In [3]:
X=dataset.drop(['output'],axis=1)
y = dataset.output

In [4]:
import numpy as np
np.random.seed(2)
features_num = ["age","trtbps","chol","thalachh","oldpeak"]

features_cat = ['sex','exng','caa','cp','fbs','restecg','slp','thall']
random_state=2

transformer_num = make_pipeline(
    StandardScaler(),
)

transformer_cat = make_pipeline(
    OneHotEncoder(handle_unknown='ignore'),
)

preprocessor = make_column_transformer(
    (transformer_num, features_num),
    (transformer_cat, features_cat),
)

X_train, X_valid, y_train, y_valid =train_test_split(X, y, train_size=0.75)

X_train = preprocessor.fit_transform(X_train)
X_valid = preprocessor.transform(X_valid)

In [5]:
X_train

array([[-0.84660682, -0.08794159,  0.09878778, ...,  0.        ,
         1.        ,  0.        ],
       [-0.51753191, -0.14385963, -0.98905483, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.57938447,  0.75082902,  0.65225156, ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [-2.8210563 , -0.08794159, -0.83637517, ...,  0.        ,
         1.        ,  0.        ],
       [-0.51753191, -0.64712199, -0.55010079, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.90845938, -0.08794159,  0.11787274, ...,  0.        ,
         0.        ,  1.        ]])

In [6]:
X_train[2]

array([ 0.57938447,  0.75082902,  0.65225156, -0.33481738,  1.46180457,
        0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
        0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
        0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  1.        ])

In [7]:
tf.keras.utils.set_random_seed(1337)

In [8]:
ann = tf.keras.models.Sequential()

In [9]:
input_shape = [X_train.shape[1]]

In [10]:
ann.add(tf.keras.layers.Dense(units=13, activation='relu',
                              input_shape=input_shape))
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))
ann.add(tf.keras.layers.Dense(units=16, activation='relu'))
ann.add(tf.keras.layers.Dense(units=16, activation='relu'))
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', 
            metrics = ['accuracy'])

In [11]:
early_stopping1 = tf.keras.callbacks.EarlyStopping(
    monitor='loss',
    patience=10,
    min_delta=0.01,
    restore_best_weights=True,
    mode='min'
) 

ACCURACY_THRESHOLD = 0.91

class myCallback(tf.keras.callbacks.Callback): 
    def on_epoch_end(self, epoch, logs={}): 
        if(logs.get('accuracy') > ACCURACY_THRESHOLD):   
            self.model.stop_training = True
        
early_stopping2= myCallback()

In [12]:
start=time.time()
ann.fit(X_train,
        y_train,
        batch_size = 128,
        epochs = 140,
        callbacks=[early_stopping1,early_stopping2])
end=time.time()
sure=end-start

Epoch 1/140
2/2 [==============================] - 0s 10ms/step - loss: 0.6925 - accuracy: 0.5374
Epoch 2/140
2/2 [==============================] - 0s 2ms/step - loss: 0.6891 - accuracy: 0.5771
Epoch 3/140
2/2 [==============================] - 0s 2ms/step - loss: 0.6859 - accuracy: 0.5859
Epoch 4/140
2/2 [==============================] - 0s 2ms/step - loss: 0.6827 - accuracy: 0.5859
Epoch 5/140
2/2 [==============================] - 0s 2ms/step - loss: 0.6791 - accuracy: 0.5815
Epoch 6/140
2/2 [==============================] - 0s 2ms/step - loss: 0.6759 - accuracy: 0.5859
Epoch 7/140
2/2 [==============================] - 0s 999us/step - loss: 0.6723 - accuracy: 0.5815
Epoch 8/140
2/2 [==============================] - 0s 3ms/step - loss: 0.6684 - accuracy: 0.5815
Epoch 9/140
2/2 [==============================] - 0s 2ms/step - loss: 0.6639 - accuracy: 0.5683
Epoch 10/140
2/2 [==============================] - 0s 996us/step - loss: 0.6598 - accuracy: 0.5683
Epoch 11/140
2/2 [======

2/2 [==============================] - 0s 997us/step - loss: 0.2549 - accuracy: 0.8899
Epoch 85/140
2/2 [==============================] - 0s 2ms/step - loss: 0.2523 - accuracy: 0.8899
Epoch 86/140
2/2 [==============================] - 0s 997us/step - loss: 0.2486 - accuracy: 0.8855
Epoch 87/140
2/2 [==============================] - 0s 2ms/step - loss: 0.2458 - accuracy: 0.8899
Epoch 88/140
2/2 [==============================] - 0s 1ms/step - loss: 0.2426 - accuracy: 0.8855
Epoch 89/140
2/2 [==============================] - 0s 998us/step - loss: 0.2394 - accuracy: 0.8943
Epoch 90/140
2/2 [==============================] - 0s 997us/step - loss: 0.2363 - accuracy: 0.9031
Epoch 91/140
2/2 [==============================] - 0s 3ms/step - loss: 0.2336 - accuracy: 0.9031
Epoch 92/140
2/2 [==============================] - 0s 998us/step - loss: 0.2302 - accuracy: 0.9031
Epoch 93/140
2/2 [==============================] - 0s 2ms/step - loss: 0.2272 - accuracy: 0.9031
Epoch 94/140
2/2 [=====

In [ ]:
sure

In [13]:
print(f'Kalp Krizi Tahmini Model egitim Başarısı: {ann.evaluate(X_train,y_train)}')

8/8 [==============================] - 0s 854us/step - loss: 0.2216 - accuracy: 0.9119
Kalp Krizi Tahmini Model egitim Başarısı: [0.2215624898672104, 0.9118942618370056]


In [14]:
print(f'Kalp Krizi Tahmini Model Test Başarısı: {ann.evaluate(X_valid,y_valid)}')

3/3 [==============================] - 0s 1ms/step - loss: 0.3010 - accuracy: 0.8816
Kalp Krizi Tahmini Model Test Başarısı: [0.30102217197418213, 0.8815789222717285]


In [15]:
0.9119-0.8816

0.030299999999999994

In [ ]:
help(tf)

In [16]:
from tensorflow.keras.models import load_model

In [17]:
ann.save('heart_attack_model.h5')

In [18]:
new_model = load_model('heart_attack_model.h5')

In [19]:
X_valid[:1]

array([[-0.188457  , -0.08794159, -0.03480693,  1.02946167, -0.88091602,
         0.        ,  1.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.        ]])

In [20]:
X_valid[0]

array([-0.188457  , -0.08794159, -0.03480693,  1.02946167, -0.88091602,
        0.        ,  1.        ,  1.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
        0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
        1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.        ,  0.        ,  0.        ,  1.        ,  0.        ])

In [21]:
new_model.predict(X_valid[:1])

1/1 [==============================] - 0s 64ms/step


array([[0.95741785]], dtype=float32)

In [23]:
y_valid

99     1
296    0
89     1
30     1
234    0
      ..
163    1
203    0
201    0
54     1
4      1
Name: output, Length: 76, dtype: int64

In [25]:
len(X_valid)

76

In [24]:
predictions = new_model.predict(X_valid)
predictions

3/3 [==============================] - 0s 998us/step


array([[0.95741785],
       [0.95436454],
       [0.89148045],
       [0.98473966],
       [0.04931707],
       [0.08463765],
       [0.9910555 ],
       [0.7299789 ],
       [0.03751437],
       [0.8733732 ],
       [0.01713705],
       [0.9908648 ],
       [0.06813556],
       [0.01201845],
       [0.9955396 ],
       [0.99017537],
       [0.03391096],
       [0.9873282 ],
       [0.01097753],
       [0.07975142],
       [0.9223025 ],
       [0.9323518 ],
       [0.16073677],
       [0.5412603 ],
       [0.03420552],
       [0.9800711 ],
       [0.9972645 ],
       [0.075269  ],
       [0.09587487],
       [0.9875573 ],
       [0.98439676],
       [0.9973967 ],
       [0.19775283],
       [0.08906271],
       [0.9669225 ],
       [0.00607961],
       [0.9196275 ],
       [0.8689356 ],
       [0.03594502],
       [0.0774895 ],
       [0.9980506 ],
       [0.962878  ],
       [0.05507975],
       [0.01701274],
       [0.9962879 ],
       [0.07064691],
       [0.10721869],
       [0.858

In [26]:
dataset

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

In [27]:
results = y_valid.values
results

array([1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1], dtype=int64)

In [ ]:
for i in range(76):
    print(f'Our prediction {predictions[i]} versus reality {results[i]}')

In [ ]:
predictions.shape

In [ ]:
predictions